namespace CrownsGuard.Core.SimulatedBoard;

public enum FigureId : byte
{
    Empty = 0,
    Fire = 1,
    LastWalkableFigure = 7,
    
    Wall = 8,
    LastNonAttackableFigure = 15,
    
    Trench = 16,
    Explosives = 17,
    LastNeutralFigure = 31,
    
    MountedKnight = 32,
    MountedArcher,
    CamelArcher,
    Knight,
    Ninja,
    Chinese,
    LegionarySword,
    King,
    Queen,
    Whiplash,
    JapanArcher,
    Archer,
    Miner,
    LegionaryPike,
    Peasant,
    Spearman,
    Warhammer,
    Crossbow,
    Cannon,
    Catapult,
    Pikeman,
    Dragon,
    Priest,
    Elephant,
    BattleAxe,
    Samurai,
    Nordguard,
    Dogs,
    Blade,
    Musketeer,
    Wizzard,
    Builder,
    Scout,
    Trader,
    Barbarian,
    Alchemist,
    Bard,
    Spartan,
    Ranger,
    Mage,
    CamelRider,
}