<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <Version>4.0.2</Version>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BattleChess3.Game\BattleChess3.Game.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Resources\Maps\**"/>
        <Content Include="Resources\Maps\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Update="Resources\TeamBoard.map">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="8.0.0" />
    </ItemGroup>

</Project>
