<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <RootNamespace>BattleChess3.ValinorTheme</RootNamespace>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Images\**"/>
        <Resource Include="Images\**"/>
    </ItemGroup>

</Project>
