<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <Version>4.0.2</Version>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="BattleChess3.Game.Test" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BattleChess3.Core\BattleChess3.Core.csproj" />
    </ItemGroup>
</Project>
