namespace CrownsGuard.FigureDefinitions;

public static class CrossFireFigureIds
{
    public const int EmptyId = 0;
    public const int PikemanId = 1;
    public const int MusketeerId = 2;
    public const int WizzardId = 3;
    public const int BuilderId = 4;
    public const int ScoutId = 5;
    public const int TraderId = 6;
    public const int WallId = 7;
    public const int BarbarianId = 8;
    public const int ExplosivesId = 9;
    public const int AlchemistId = 10;
    public const int BardId = 11;
    public const int SpartanId = 12;
    public const int RangerId = 13;
    public const int MageId = 14;
    public const int CamelRiderId = 15;
    public const int MountedKnightId = 16;
    public const int MountedArcherId = 17;
    public const int CamelArcherId = 18;
    public const int KnightId = 19;
    public const int NinjaId = 20;
    public const int ChineseId = 21;
    public const int LegionarySwordId = 22;
    public const int KingId = 23;
    public const int QueenId = 24;
    public const int WhiplashId = 25;
    public const int JapanArcherId = 26;
    public const int ArcherId = 27;
    public const int TrenchId = 28;
    public const int MinerId = 29;
    public const int LegionaryPikeId = 30;
    public const int PeasantId = 31;
    public const int SpearmanId = 32;
    public const int WarhammerId = 33;
    // public const int Id = 34;
    public const int CrossbowId = 35;
    public const int CannonId = 36;
    public const int CatapultId = 37;
    public const int FireId = 38;
    public const int DragonId = 39;
    public const int PriestId = 40;
    public const int ElephantId = 41;
    public const int BattleAxeId = 42;
    public const int SamuraiId = 43;
    public const int NordguardId = 44;
    public const int DogsId = 45;
    public const int BladeId = 46;
}