namespace CrownsGuard.FigureDefinitions;

[Flags]
public enum CrownsGuardFigureIds
{
    EmptyId = 0,
    PikemanId = 1,
    MusketeerId = 2,
    WizzardId = 3,
    BuilderId = 4,
    ScoutId = 5,
    TraderId = 6,
    WallId = 7,
    BarbarianId = 8,
    ExplosivesId = 9,
    AlchemistId = 10,
    BardId = 11,
    SpartanId = 12,
    RangerId = 13,
    MageId = 14,
    CamelRiderId = 15,
    MountedKnightId = 16,
    MountedArcherId = 17,
    CamelArcherId = 18,
    KnightId = 19,
    NinjaId = 20,
    ChineseId = 21,
    LegionarySwordId = 22,
    KingId = 23,
    QueenId = 24,
    WhiplashId = 25,
    JapanArcherId = 26,
    ArcherId = 27,
    TrenchId = 28,
    MinerId = 29,
    LegionaryPikeId = 30,
    PeasantId = 31,
    SpearmanId = 32,
    WarhammerId = 33,
    // Id = 34,
    CrossbowId = 35,
    CannonId = 36,
    CatapultId = 37,
    FireId = 38,
    DragonId = 39,
    PriestId = 40,
    ElephantId = 41,
    BattleAxeId = 42,
    SamuraiId = 43,
    NordguardId = 44,
    DogsId = 45,
    BladeId = 46,
}