//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleChess3.StarWarsFigures.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleChess3.StarWarsFigures.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬛
        ///⬛⬜⬜⬜⬜⬜⬛⬜
        ///⬜⬛⬜⬜⬜⬛⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///.
        /// </summary>
        internal static string AhsokaVentress_Description {
            get {
                return ResourceManager.GetString("AhsokaVentress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop.
        /// </summary>
        internal static string AhsokaVentress_Name {
            get {
                return ResourceManager.GetString("AhsokaVentress_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬜⬜⬛▣⬛⬜⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///
        ///Special: Can castle with rook
        ///.
        /// </summary>
        internal static string AnakinGrievus_Description {
            get {
                return ResourceManager.GetString("AnakinGrievus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string AnakinGrievus_Name {
            get {
                return ResourceManager.GetString("AnakinGrievus_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Bomb_Description {
            get {
                return ResourceManager.GetString("Bomb_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Bomb_Name {
            get {
                return ResourceManager.GetString("Bomb_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬜⬜⬛⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬛⬜⬜⬜⬛⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///.
        /// </summary>
        internal static string CodyBane_Description {
            get {
                return ResourceManager.GetString("CodyBane_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string CodyBane_Name {
            get {
                return ResourceManager.GetString("CodyBane_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬛⬜⬜⬜⬛
        ///⬛⬜⬜⬛⬜⬜⬛⬜
        ///⬜⬛⬜⬛⬜⬛⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬛⬛⬛▣⬛⬛⬛⬛
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬛⬜⬜
        ///⬛⬜⬜⬛⬜⬜⬛⬜
        ///.
        /// </summary>
        internal static string ObiwanPalpatine_Description {
            get {
                return ResourceManager.GetString("ObiwanPalpatine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        internal static string ObiwanPalpatine_Name {
            get {
                return ResourceManager.GetString("ObiwanPalpatine_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬛⬛⬛▣⬛⬛⬛⬛
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///.
        /// </summary>
        internal static string PadmeAurra_Description {
            get {
                return ResourceManager.GetString("PadmeAurra_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook.
        /// </summary>
        internal static string PadmeAurra_Name {
            get {
                return ResourceManager.GetString("PadmeAurra_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Soldiers_Description {
            get {
                return ResourceManager.GetString("Soldiers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Soldiers_Name {
            get {
                return ResourceManager.GetString("Soldiers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Special_Description {
            get {
                return ResourceManager.GetString("Special_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Special_Name {
            get {
                return ResourceManager.GetString("Special_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star wars.
        /// </summary>
        internal static string StarWarsFigureGroup_Name {
            get {
                return ResourceManager.GetString("StarWarsFigureGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn
        ///
        ///Move:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///
        ///Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///      
        ///Special: If initial position, can move further
        ///Special: If on last tile, changes to Queen
        ///.
        /// </summary>
        internal static string YodaDooku_Description {
            get {
                return ResourceManager.GetString("YodaDooku_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn.
        /// </summary>
        internal static string YodaDooku_Name {
            get {
                return ResourceManager.GetString("YodaDooku_Name", resourceCulture);
            }
        }
    }
}
