<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>Latest</LangVersion>
        <Version>4.0.2</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentResults" Version="4.0.0" />
      <PackageReference Include="MongoDB.Driver" Version="3.4.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CrownsGuard.Database\CrownsGuard.Database.csproj" />
      <ProjectReference Include="..\CrownsGuard.Game\CrownsGuard.Game.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DatabaseAccess\" />
    </ItemGroup>

</Project>
