<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>BattleChess3</AssemblyName>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
        <LangVersion>default</LangVersion>
        <Version>4.0.2</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BattleChess3.Game\BattleChess3.Game.csproj" />
        <ProjectReference Include="..\BattleChess3.Maps\BattleChess3.Maps.csproj" />
        <ProjectReference Include="..\BattleChess3.Multiplayer\BattleChess3.Multiplayer.csproj" />
        <ProjectReference Include="..\FigureSets\BattleChess3.CrossFire\BattleChess3.CrossFireFigures.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="BattleChess3.deps.json"/>
        <None Update="Resources\Sounds\Chess1.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Chess2.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Chess3.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Chess4.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Chess5.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Chess6.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Rolling.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Rolling1.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Rolling2.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Button1.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Error.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Background1.mp3">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Background2.mp3">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Background3.mp3">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Background4.mp3">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Background5.mp3">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Sounds\Background6.mp3">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.0.0" />
        <PackageReference Include="Autofac.Extras.CommonServiceLocator" Version="6.1.0" />
        <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Nicenis" Version="1.3.6" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Settings.Designer.cs">
            <DesignTimeSharedInput>True</DesignTimeSharedInput>
            <AutoGen>True</AutoGen>
            <DependentUpon>Settings.settings</DependentUpon>
        </Compile>
        <Compile Update="Resources\Strings.Designer.cs">
            <DependentUpon>Strings.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <None Update="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Page Update="Resources\Styles.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Game\BoardTileControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Menu\SignUpControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Menu\MenuControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Menu\LeaderboardControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Menu\LoginControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Editor\TeamBoardControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Game\UnitInfoControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Menu\LobbyControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Game\GameSideControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Game\GameBoardControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Editor\EditorUnitsControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Editor\EditorRightControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="MainWindow\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="MainWindow\LoadingControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="MainWindow\NotificationControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Images\*" />
        <None Remove="Images\*" />
        <Resource Include="Resources\Images\ApplicationBackground.jpg" />
        <Resource Include="Resources\Images\ButtonBlueBackground.jpg" />
        <Resource Include="Resources\Images\ButtonGreen2Background.jpg" />
        <Resource Include="Resources\Images\ButtonGreen3Background.jpg" />
        <Resource Include="Resources\Images\ButtonGreenBackground.jpg" />
        <Resource Include="Resources\Images\ButtonOrange2Background.jpg" />
        <Resource Include="Resources\Images\ButtonOrange3Background.jpg" />
        <Resource Include="Resources\Images\ButtonOrangeBackground.jpg" />
        <Resource Include="Resources\Images\ButtonPurple2Background.jpg" />
        <Resource Include="Resources\Images\ButtonPurpleBackground.jpg" />
        <Resource Include="Resources\Images\ButtonRed2Background.png" />
        <Resource Include="Resources\Images\ButtonRedBackground.jpg" />
        <Resource Include="Resources\Images\ButtonWhiteBackground.jpg" />
        <Resource Include="Resources\Images\ChessTileCanGo.png" />
        <Resource Include="Resources\Images\ChessTileDangered.png" />
        <Resource Include="Resources\Images\ChessTileKingBase.png" />
        <Resource Include="Resources\Images\ChessTileKingDangered.png" />
        <Resource Include="Resources\Images\ChessTileKingMouseOn.png" />
        <Resource Include="Resources\Images\ChessTileKingSelected.png" />
        <Resource Include="Resources\Images\ChessTileKingSpecial.png" />
        <Resource Include="Resources\Images\ChessTileMouseOn.png" />
        <Resource Include="Resources\Images\ChessTileOutsideBoard.png" />
        <Resource Include="Resources\Images\ChessTileSelected.png" />
        <Resource Include="Resources\Images\ChessTileSpecial.png" />
        <Resource Include="Resources\Images\DefaultButton.png" />
        <Resource Include="Resources\Images\DefaultButtonMouseOn.png" />
        <Resource Include="Resources\Images\Preview.png" />
    </ItemGroup>
</Project>