//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleChess3.DisneyFigures.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleChess3.DisneyFigures.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬛
        ///⬛⬜⬜⬜⬜⬜⬛⬜
        ///⬜⬛⬜⬜⬜⬛⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///
        ///Special: Can take friendly units.
        /// </summary>
        internal static string DisneyBishop_Description {
            get {
                return ResourceManager.GetString("DisneyBishop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop.
        /// </summary>
        internal static string DisneyBishop_Name {
            get {
                return ResourceManager.GetString("DisneyBishop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disney.
        /// </summary>
        internal static string DisneyFigureGroup_Name {
            get {
                return ResourceManager.GetString("DisneyFigureGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬜⬜⬛▣⬛⬜⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///
        ///Special: Can castle with rook
        ///Special: Can take friendly units.
        /// </summary>
        internal static string DisneyKing_Description {
            get {
                return ResourceManager.GetString("DisneyKing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string DisneyKing_Name {
            get {
                return ResourceManager.GetString("DisneyKing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬜⬜⬛⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬛⬜⬜⬜⬛⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///
        ///Special: Can take friendly units.
        /// </summary>
        internal static string DisneyKnight_Description {
            get {
                return ResourceManager.GetString("DisneyKnight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string DisneyKnight_Name {
            get {
                return ResourceManager.GetString("DisneyKnight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn
        ///
        ///Move:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///
        ///Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///      
        ///Special: If initial position, can move further
        ///Special: If on last tile, changes to Queen
        ///Special: Can take friendly units.
        /// </summary>
        internal static string DisneyPawn_Description {
            get {
                return ResourceManager.GetString("DisneyPawn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn.
        /// </summary>
        internal static string DisneyPawn_Name {
            get {
                return ResourceManager.GetString("DisneyPawn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬛⬜⬜⬜⬛
        ///⬛⬜⬜⬛⬜⬜⬛⬜
        ///⬜⬛⬜⬛⬜⬛⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬛⬛⬛▣⬛⬛⬛⬛
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬛⬜⬜
        ///⬛⬜⬜⬛⬜⬜⬛⬜
        ///
        ///Special: Can take friendly units.
        /// </summary>
        internal static string DisneyQueen_Description {
            get {
                return ResourceManager.GetString("DisneyQueen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        internal static string DisneyQueen_Name {
            get {
                return ResourceManager.GetString("DisneyQueen_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook
        ///
        ///Move + Attack:
        ///
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬛⬛⬛▣⬛⬛⬛⬛
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///
        ///Special: Can take friendly units.
        /// </summary>
        internal static string DisneyRook_Description {
            get {
                return ResourceManager.GetString("DisneyRook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook.
        /// </summary>
        internal static string DisneyRook_Name {
            get {
                return ResourceManager.GetString("DisneyRook_Name", resourceCulture);
            }
        }
    }
}
